#!/usr/bin/env bash

composer normalize --dry-run composer.json
composer normalize --dry-run src/Acclaim/composer.json
composer normalize --dry-run src/Admitad/composer.json
composer normalize --dry-run src/Amazon/composer.json
composer normalize --dry-run src/AngelList/composer.json
composer normalize --dry-run src/AppNet/composer.json
composer normalize --dry-run src/Apple/composer.json
composer normalize --dry-run src/ArcGIS/composer.json
composer normalize --dry-run src/Asana/composer.json
composer normalize --dry-run src/Auth0/composer.json
composer normalize --dry-run src/Aweber/composer.json
composer normalize --dry-run src/Azure/composer.json
composer normalize --dry-run src/Battlenet/composer.json
composer normalize --dry-run src/Bitbucket/composer.json
composer normalize --dry-run src/Bitly/composer.json
composer normalize --dry-run src/Box/composer.json
composer normalize --dry-run src/Buffer/composer.json
composer normalize --dry-run src/CampaignMonitor/composer.json
composer normalize --dry-run src/Cheddar/composer.json
composer normalize --dry-run src/ClaveUnica/composer.json
composer normalize --dry-run src/Coinbase/composer.json
composer normalize --dry-run src/ConstantContact/composer.json
composer normalize --dry-run src/Coursera/composer.json
composer normalize --dry-run src/Dailymotion/composer.json
composer normalize --dry-run src/Dataporten/composer.json
composer normalize --dry-run src/Deezer/composer.json
composer normalize --dry-run src/Deviantart/composer.json
composer normalize --dry-run src/DigitalOcean/composer.json
composer normalize --dry-run src/Discogs/composer.json
composer normalize --dry-run src/Discord/composer.json
composer normalize --dry-run src/Disqus/composer.json
composer normalize --dry-run src/Douban/composer.json
composer normalize --dry-run src/Dribbble/composer.json
composer normalize --dry-run src/Dropbox/composer.json
composer normalize --dry-run src/Envato/composer.json
composer normalize --dry-run src/Etsy/composer.json
composer normalize --dry-run src/Eventbrite/composer.json
composer normalize --dry-run src/EyeEm/composer.json
composer normalize --dry-run src/Facebook/composer.json
composer normalize --dry-run src/Faceit/composer.json
composer normalize --dry-run src/Fitbit/composer.json
composer normalize --dry-run src/FiveHundredPixel/composer.json
composer normalize --dry-run src/Flattr/composer.json
composer normalize --dry-run src/Flexkids/composer.json
composer normalize --dry-run src/Flickr/composer.json
composer normalize --dry-run src/Foursquare/composer.json
composer normalize --dry-run src/FranceConnect/composer.json
composer normalize --dry-run src/GarminConnect/composer.json
composer normalize --dry-run src/GettyImages/composer.json
composer normalize --dry-run src/GitHub/composer.json
composer normalize --dry-run src/GitLab/composer.json
composer normalize --dry-run src/Gitee/composer.json
composer normalize --dry-run src/Goodreads/composer.json
composer normalize --dry-run src/Google/composer.json
composer normalize --dry-run src/Graph/composer.json
composer normalize --dry-run src/Harvest/composer.json
composer normalize --dry-run src/HeadHunter/composer.json
composer normalize --dry-run src/Heroku/composer.json
composer normalize --dry-run src/HubSpot/composer.json
composer normalize --dry-run src/HumanApi/composer.json
composer normalize --dry-run src/IFSP/composer.json
composer normalize --dry-run src/Imgur/composer.json
composer normalize --dry-run src/Instagram/composer.json
composer normalize --dry-run src/InstagramBasic/composer.json
composer normalize --dry-run src/Intercom/composer.json
composer normalize --dry-run src/Jira/composer.json
composer normalize --dry-run src/Kakao/composer.json
composer normalize --dry-run src/Keycloak/composer.json
composer normalize --dry-run src/LaravelPassport/composer.json
composer normalize --dry-run src/Line/composer.json
composer normalize --dry-run src/LinkedIn/composer.json
composer normalize --dry-run src/Live/composer.json
composer normalize --dry-run src/MailChimp/composer.json
composer normalize --dry-run src/Mailru/composer.json
composer normalize --dry-run src/MakerLog/composer.json
composer normalize --dry-run src/Mattermost/composer.json
composer normalize --dry-run src/MediaCube/composer.json
composer normalize --dry-run src/Medium/composer.json
composer normalize --dry-run src/Meetup/composer.json
composer normalize --dry-run src/Microsoft/composer.json
composer normalize --dry-run src/Mixcloud/composer.json
composer normalize --dry-run src/MoiKrug/composer.json
composer normalize --dry-run src/Mollie/composer.json
composer normalize --dry-run src/Naver/composer.json
composer normalize --dry-run src/Netlify/composer.json
composer normalize --dry-run src/Nocks/composer.json
composer normalize --dry-run src/OAuthgen/composer.json
composer normalize --dry-run src/OSChina/composer.json
composer normalize --dry-run src/Odnoklassniki/composer.json
composer normalize --dry-run src/Okta/composer.json
composer normalize --dry-run src/Orcid/composer.json
composer normalize --dry-run src/Patreon/composer.json
composer normalize --dry-run src/PayPal/composer.json
composer normalize --dry-run src/PayPalSandbox/composer.json
composer normalize --dry-run src/Paymill/composer.json
composer normalize --dry-run src/PeeringDB/composer.json
composer normalize --dry-run src/Pinterest/composer.json
composer normalize --dry-run src/Pipedrive/composer.json
composer normalize --dry-run src/Podio/composer.json
composer normalize --dry-run src/Procore/composer.json
composer normalize --dry-run src/ProductHunt/composer.json
composer normalize --dry-run src/ProjectV/composer.json
composer normalize --dry-run src/Pushbullet/composer.json
composer normalize --dry-run src/QQ/composer.json
composer normalize --dry-run src/QuickBooks/composer.json
composer normalize --dry-run src/Readability/composer.json
composer normalize --dry-run src/Redbooth/composer.json
composer normalize --dry-run src/Reddit/composer.json
composer normalize --dry-run src/RunKeeper/composer.json
composer normalize --dry-run src/SURFconext/composer.json
composer normalize --dry-run src/Sage/composer.json
composer normalize --dry-run src/SalesForce/composer.json
composer normalize --dry-run src/SciStarter/composer.json
composer normalize --dry-run src/SharePoint/composer.json
composer normalize --dry-run src/Shopify/composer.json
composer normalize --dry-run src/Slack/composer.json
composer normalize --dry-run src/Smashcast/composer.json
composer normalize --dry-run src/Snapchat/composer.json
composer normalize --dry-run src/SoundCloud/composer.json
composer normalize --dry-run src/Spotify/composer.json
composer normalize --dry-run src/StackExchange/composer.json
composer normalize --dry-run src/Steam/composer.json
composer normalize --dry-run src/Steem/composer.json
composer normalize --dry-run src/StockTwits/composer.json
composer normalize --dry-run src/Strava/composer.json
composer normalize --dry-run src/Stripe/composer.json
composer normalize --dry-run src/TVShowTime/composer.json
composer normalize --dry-run src/TeamService/composer.json
composer normalize --dry-run src/Teamleader/composer.json
composer normalize --dry-run src/Teamweek/composer.json
composer normalize --dry-run src/ThirtySevenSignals/composer.json
composer normalize --dry-run src/Todoist/composer.json
composer normalize --dry-run src/Trakt/composer.json
composer normalize --dry-run src/Trello/composer.json
composer normalize --dry-run src/Tumblr/composer.json
composer normalize --dry-run src/TwentyThreeAndMe/composer.json
composer normalize --dry-run src/Twitch/composer.json
composer normalize --dry-run src/Twitter/composer.json
composer normalize --dry-run src/UCL/composer.json
composer normalize --dry-run src/UFS/composer.json
composer normalize --dry-run src/Uber/composer.json
composer normalize --dry-run src/Ufutx/composer.json
composer normalize --dry-run src/Unsplash/composer.json
composer normalize --dry-run src/Untappd/composer.json
composer normalize --dry-run src/VKontakte/composer.json
composer normalize --dry-run src/Venmo/composer.json
composer normalize --dry-run src/Vercel/composer.json
composer normalize --dry-run src/VersionOne/composer.json
composer normalize --dry-run src/Vimeo/composer.json
composer normalize --dry-run src/WeChatServiceAccount/composer.json
composer normalize --dry-run src/WeChatWeb/composer.json
composer normalize --dry-run src/Weibo/composer.json
composer normalize --dry-run src/Weixin/composer.json
composer normalize --dry-run src/WeixinWeb/composer.json
composer normalize --dry-run src/Withings/composer.json
composer normalize --dry-run src/WordPress/composer.json
composer normalize --dry-run src/Xero/composer.json
composer normalize --dry-run src/Xing/composer.json
composer normalize --dry-run src/Yahoo/composer.json
composer normalize --dry-run src/Yammer/composer.json
composer normalize --dry-run src/Yandex/composer.json
composer normalize --dry-run src/Yiban/composer.json
composer normalize --dry-run src/YouTube/composer.json
composer normalize --dry-run src/Zalo/composer.json
composer normalize --dry-run src/Zendesk/composer.json
composer normalize --dry-run src/Zoho/composer.json
composer normalize --dry-run src/xREL/composer.json
