#!/usr/bin/env bash

composer validate --strict composer.json
composer validate --strict src/Acclaim/composer.json
composer validate --strict src/Admitad/composer.json
composer validate --strict src/Amazon/composer.json
composer validate --strict src/AngelList/composer.json
composer validate --strict src/AppNet/composer.json
composer validate --strict src/Apple/composer.json
composer validate --strict src/ArcGIS/composer.json
composer validate --strict src/Asana/composer.json
composer validate --strict src/Auth0/composer.json
composer validate --strict src/Aweber/composer.json
composer validate --strict src/Azure/composer.json
composer validate --strict src/Battlenet/composer.json
composer validate --strict src/Bitbucket/composer.json
composer validate --strict src/Bitly/composer.json
composer validate --strict src/Box/composer.json
composer validate --strict src/Buffer/composer.json
composer validate --strict src/CampaignMonitor/composer.json
composer validate --strict src/Cheddar/composer.json
composer validate --strict src/ClaveUnica/composer.json
composer validate --strict src/Coinbase/composer.json
composer validate --strict src/ConstantContact/composer.json
composer validate --strict src/Coursera/composer.json
composer validate --strict src/Dailymotion/composer.json
composer validate --strict src/Dataporten/composer.json
composer validate --strict src/Deezer/composer.json
composer validate --strict src/Deviantart/composer.json
composer validate --strict src/DigitalOcean/composer.json
composer validate --strict src/Discogs/composer.json
composer validate --strict src/Discord/composer.json
composer validate --strict src/Disqus/composer.json
composer validate --strict src/Douban/composer.json
composer validate --strict src/Dribbble/composer.json
composer validate --strict src/Dropbox/composer.json
composer validate --strict src/Envato/composer.json
composer validate --strict src/Etsy/composer.json
composer validate --strict src/Eventbrite/composer.json
composer validate --strict src/EyeEm/composer.json
composer validate --strict src/Facebook/composer.json
composer validate --strict src/Faceit/composer.json
composer validate --strict src/Fitbit/composer.json
composer validate --strict src/FiveHundredPixel/composer.json
composer validate --strict src/Flattr/composer.json
composer validate --strict src/Flexkids/composer.json
composer validate --strict src/Flickr/composer.json
composer validate --strict src/Foursquare/composer.json
composer validate --strict src/FranceConnect/composer.json
composer validate --strict src/GarminConnect/composer.json
composer validate --strict src/GettyImages/composer.json
composer validate --strict src/GitHub/composer.json
composer validate --strict src/GitLab/composer.json
composer validate --strict src/Gitee/composer.json
composer validate --strict src/Goodreads/composer.json
composer validate --strict src/Google/composer.json
composer validate --strict src/Graph/composer.json
composer validate --strict src/Harvest/composer.json
composer validate --strict src/HeadHunter/composer.json
composer validate --strict src/Heroku/composer.json
composer validate --strict src/HubSpot/composer.json
composer validate --strict src/HumanApi/composer.json
composer validate --strict src/IFSP/composer.json
composer validate --strict src/Imgur/composer.json
composer validate --strict src/Instagram/composer.json
composer validate --strict src/InstagramBasic/composer.json
composer validate --strict src/Intercom/composer.json
composer validate --strict src/Jira/composer.json
composer validate --strict src/Kakao/composer.json
composer validate --strict src/Keycloak/composer.json
composer validate --strict src/LaravelPassport/composer.json
composer validate --strict src/Line/composer.json
composer validate --strict src/LinkedIn/composer.json
composer validate --strict src/Live/composer.json
composer validate --strict src/MailChimp/composer.json
composer validate --strict src/Mailru/composer.json
composer validate --strict src/MakerLog/composer.json
composer validate --strict src/Mattermost/composer.json
composer validate --strict src/MediaCube/composer.json
composer validate --strict src/Medium/composer.json
composer validate --strict src/Meetup/composer.json
composer validate --strict src/Microsoft/composer.json
composer validate --strict src/Mixcloud/composer.json
composer validate --strict src/MoiKrug/composer.json
composer validate --strict src/Mollie/composer.json
composer validate --strict src/Naver/composer.json
composer validate --strict src/Netlify/composer.json
composer validate --strict src/Nocks/composer.json
composer validate --strict src/OAuthgen/composer.json
composer validate --strict src/OSChina/composer.json
composer validate --strict src/Odnoklassniki/composer.json
composer validate --strict src/Okta/composer.json
composer validate --strict src/Orcid/composer.json
composer validate --strict src/Patreon/composer.json
composer validate --strict src/PayPal/composer.json
composer validate --strict src/PayPalSandbox/composer.json
composer validate --strict src/Paymill/composer.json
composer validate --strict src/PeeringDB/composer.json
composer validate --strict src/Pinterest/composer.json
composer validate --strict src/Pipedrive/composer.json
composer validate --strict src/Podio/composer.json
composer validate --strict src/Procore/composer.json
composer validate --strict src/ProductHunt/composer.json
composer validate --strict src/ProjectV/composer.json
composer validate --strict src/Pushbullet/composer.json
composer validate --strict src/QQ/composer.json
composer validate --strict src/QuickBooks/composer.json
composer validate --strict src/Readability/composer.json
composer validate --strict src/Redbooth/composer.json
composer validate --strict src/Reddit/composer.json
composer validate --strict src/RunKeeper/composer.json
composer validate --strict src/SURFconext/composer.json
composer validate --strict src/Sage/composer.json
composer validate --strict src/SalesForce/composer.json
composer validate --strict src/SciStarter/composer.json
composer validate --strict src/SharePoint/composer.json
composer validate --strict src/Shopify/composer.json
composer validate --strict src/Slack/composer.json
composer validate --strict src/Smashcast/composer.json
composer validate --strict src/Snapchat/composer.json
composer validate --strict src/SoundCloud/composer.json
composer validate --strict src/Spotify/composer.json
composer validate --strict src/StackExchange/composer.json
composer validate --strict src/Steam/composer.json
composer validate --strict src/Steem/composer.json
composer validate --strict src/StockTwits/composer.json
composer validate --strict src/Strava/composer.json
composer validate --strict src/Stripe/composer.json
composer validate --strict src/TVShowTime/composer.json
composer validate --strict src/TeamService/composer.json
composer validate --strict src/Teamleader/composer.json
composer validate --strict src/Teamweek/composer.json
composer validate --strict src/ThirtySevenSignals/composer.json
composer validate --strict src/Todoist/composer.json
composer validate --strict src/Trakt/composer.json
composer validate --strict src/Trello/composer.json
composer validate --strict src/Tumblr/composer.json
composer validate --strict src/TwentyThreeAndMe/composer.json
composer validate --strict src/Twitch/composer.json
composer validate --strict src/Twitter/composer.json
composer validate --strict src/UCL/composer.json
composer validate --strict src/UFS/composer.json
composer validate --strict src/Uber/composer.json
composer validate --strict src/Ufutx/composer.json
composer validate --strict src/Unsplash/composer.json
composer validate --strict src/Untappd/composer.json
composer validate --strict src/VKontakte/composer.json
composer validate --strict src/Venmo/composer.json
composer validate --strict src/Vercel/composer.json
composer validate --strict src/VersionOne/composer.json
composer validate --strict src/Vimeo/composer.json
composer validate --strict src/WeChatServiceAccount/composer.json
composer validate --strict src/WeChatWeb/composer.json
composer validate --strict src/Weibo/composer.json
composer validate --strict src/Weixin/composer.json
composer validate --strict src/WeixinWeb/composer.json
composer validate --strict src/Withings/composer.json
composer validate --strict src/WordPress/composer.json
composer validate --strict src/Xero/composer.json
composer validate --strict src/Xing/composer.json
composer validate --strict src/Yahoo/composer.json
composer validate --strict src/Yammer/composer.json
composer validate --strict src/Yandex/composer.json
composer validate --strict src/Yiban/composer.json
composer validate --strict src/YouTube/composer.json
composer validate --strict src/Zalo/composer.json
composer validate --strict src/Zendesk/composer.json
composer validate --strict src/Zoho/composer.json
composer validate --strict src/xREL/composer.json
