name: Split providers into their individual repos

on:
  push:
    branches:
      - master

jobs:
  split:
    name: Split Providers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install splitsh-lite
        run: |
          wget -qO /tmp/splitsh-lite.tar.gz https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
          tar -zxpf /tmp/splitsh-lite.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/splitsh-lite

      - name: Split packages
        run: ./tools/split.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
          MAX_PARALLEL: '8'
