name: Split providers into their individual repos

on:
  push:
    branches:
      - master

jobs:
  config:
    name: Generate Split Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate matrix
        id: set-matrix
        run: echo "matrix=$(php tools/generate-split-matrix.php)" >> $GITHUB_OUTPUT

  split:
    name: Split ${{ matrix.package }}
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.config.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          package_directory: 'src/${{ matrix.package }}'
          repository_organization: 'SocialiteProviders'
          repository_name: '${{ matrix.split_repository || matrix.package }}'
          user_email: 'socialite@atymic.dev'
          user_name: 'SocialiteProviders Bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
