name: Pull Requests

on:
  pull_request_target:
    types: [ opened ]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: SocialiteProviders/.github/.github/workflows/pull-requests.yml@main
