name: Test

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.5'
          extensions: json, mbstring

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Lint the code
        run: vendor/bin/parallel-lint --exclude vendor .

      - name: Lint composer.json
        run: composer validate --strict
